baseURL = 'https://superlative-marzipan-92f1e2.netlify.app/'
languageCode = 'en-us'
title = 'CodeNexus'
theme = "basic"
disqusShortname = "Codenexus"


[params]
autohor = "arisandi kader"
description = 'my prortfolio'
keywords = "codenexus, programing, tech,css,html"

[taxonomies]
 year = "year"
 month = "month"
 tag = "tags"
 category = "categories"

[permalinks]
 posts = "posts/:year/:month/:slug/"
 year = "/posts/:slug/"
 month = "/posts/:slug/"

 Paginate = 10

 [related]
    threshold = 10.0
    includeNewer = false
    toLower = false
    [[related.indices]]
    name = "tags"
    weight = 100.0
    [[related.indices]]
    name = "date"
    weight = 5.0
 
